name: Java  Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 8
      uses: actions/setup-java@master
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean package --file pom.xml
    - name: putjar
      run: |
          cd target
          sshpass -p 'Ab741894872' sftp -oPort=22  root@119.3.26.3 
          put -r "wechart-0.0.1-SNAPSHOT.jar"
		      # 部署到服务器
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          nohup java -jar wechart-0.0.1-SNAPSHOT.jar > wechart.log 2>&1 &
